//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::cars::Entity as Cars;
pub use super::chats::Entity as Chats;
pub use super::plants::Entity as Plants;
pub use super::species_of_plants::Entity as SpeciesOfPlants;
pub use super::users::Entity as Users;
