//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "species_of_plants")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub common_name: String,
    pub scientific_name: Option<String>,
    pub family_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub care_instructions: Option<String>,
    pub origin: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub photo_url: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::plants::Entity")]
    Plants,
}

impl Related<super::plants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plants.def()
    }
}
