-- Add migration script here
ALTER TABLE users ADD COLUMN email_public BOOLEAN DEFAULT false;
ALTER TABLE users ALTER COLUMN lat SET DEFAULT 0;
ALTER TABLE users ALTER COLUMN lon SET DEFAULT 0;
ALTER TABLE users ALTER COLUMN lat SET NOT NULL;
ALTER TABLE users ALTER COLUMN lon SET NOT NULL;
